development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: karaoke_search_development
  pool: 5
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['APP_DATABASE_PASSWORD'] %>

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: karaoke_search_test
  pool: 5
  username: <%= ENV['APP_DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: karaoke_search_production
  pool: 5
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

